putStrLn "#     # ####### #       #        #####"
putStrLn "#     # #       #       #       #     #"
putStrLn "#     # #       #       #       #     #"
putStrLn "####### #####   #       #       #     #"
putStrLn "#     # #       #       #       #     #"
putStrLn "#     # #       #       #       #     #"
putStrLn "#     # ####### ####### #######  #####"
