name: makeMistakesToLearnHaskell
version: '0.1.0.0'
synopsis: Make mistakes to learn Haskell!
category: Education
author: Yuji Yamamoto
maintainer: whosekiteneverfly@gmail.com
copyright: 2017 Yuji Yamamoto
license: Apache-2.0
homepage: https://github.com/haskell-jp/makeMistakesToLearnHaskell#readme
git: https://github.com/haskell-jp/makeMistakesToLearnHaskell.git
data-files:
- assets/*.md
- assets/*.hs
extra-source-files:
- README.md
- src/imports/*.hs
- src/test/imports/*.hs
# test data here. see https://stackoverflow.com/questions/29361413/including-data-files-only-in-cabal-test-suites
- test/assets/1/*.hs
- test/assets/common/*.hs

library:
  source-dirs: src
  default-extensions:
  - CPP
  - DeriveGeneric
  - DeriveDataTypeable
  - OverloadedStrings
  include-dirs:
  - src
  exposed-modules:
  - Education.MakeMistakesToLearnHaskell
  - Education.MakeMistakesToLearnHaskell.Env
  - Education.MakeMistakesToLearnHaskell.Evaluator.Types
  - Education.MakeMistakesToLearnHaskell.Exercise
  - Education.MakeMistakesToLearnHaskell.Exercise.Types
  # ghc-options:          -Wno-unused-imports
  # Why doesn't -Wno-unused-imports work?
  dependencies:
  - base >=4.7 && <5
  # TODO: Decide version
  - QuickCheck
  - bytestring
  - directory
  - errors
  - filepath
  - ghc-syntax-highlighter
  - hint
  - insert-ordered-containers
  # - i18n Use in the future
  - NoTrace
  - QuickCheck
  - regex-applicative
  - safe
  - text
  - transformers
  - typed-process
  - vector
  - yaml
  when:
  - condition: os(windows)
    dependencies:
    - Win32

executables:
  mmlh:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - makeMistakesToLearnHaskell
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread

tests:
  makeMistakesToLearnHaskell-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - CPP
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - makeMistakesToLearnHaskell
    - bytestring
    - directory
    - filepath
    - hspec
    - hspec-core
    - main-tester >=0.2
    - QuickCheck
    - text

flags:
  static:
    description: Pass -static/-pthread to ghc when linking the stack binary.
    manual: true
    default: false