resolver: lts-12.10
packages:
- '.'
extra-deps:
- main-tester-0.2.0.0
- NoTrace-0.3.0.3
flags: {}
extra-package-dbs: []

image:
  container:
    name: mmlh
    base: mmlh-run
    add:
      assets: /app/assets
      test/assets: /app/test/assets
      scripts/docker: /usr/local/bin/
    entrypoints: ["entrypoint.sh"]