{-# LANGUAGE TemplateHaskell #-}

module Education.MakeMistakesToLearnHaskell.Commons.Exercise where

import qualified Data.Aeson.TH  as AT
import           Data.Text.Lazy (Text)


-- | Detailed error message generated by GHC
--   (and by 'Education.MakeMistakesToLearnHaskell.Exercise.Types.Diagnosis')
type Details = Text

-- | Source code given by the user.
type SourceCode = Text

-- | The name of source code (usually 'FilePath') given by the user.
type Name = String


data FailBy =
    WrongOutput !Details
  | CompileError
      !Details -- ^ Output by GHC
      !Details -- ^ Diagnosis message
  deriving (Eq, Show)

$(AT.deriveJSON AT.defaultOptions ''FailBy)
